version: "v3.1.0"

services:
  app:
    build: ./app
    container_name: dashboard
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app/src:/var/www/html:cached
    restart: unless-stopped
    networks:
      - dashboard_net
  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - "5432"
    networks:
      - dashboard_net
networks:
  dashboard_net:
    driver: bridge
